### ISSUE TITLE
[Visual Issue] Vehicle Dashboard expenses breakdown doesn't scale down well to laptop screen size

### ISSUE THREAD

**Issue by mr-adult** [hargata/lubelog#111]
On the vehicle dashboard, my expense breakdown is scrunched in pretty tight and cutting off some of the edges of the various elements.

![Screenshot from 2024-01-16 19-42-37](https://github.com/hargata/lubelog/assets/110244689/31872e0d-5820-40a7-96a2-d69294974fab)

**Comment by mr-adult** [comment]
This is in the Firefox browser

**Comment by hargata** [comment]
this is _somewhat_ fixed. I cut down on the labels so that they're no longer cut off, but the way ChartJS renders the pie charts doesn't allow me a lot of flexibility to determine how much room should the pie take and how much room the labels should take. The good news tho is that if viewed on a smaller screen(e.g. Mobile) the chart will take up the full screen width, it seems to be only an issue on smaller laptop screens.

**Comment by mr-adult** [comment]
Thank you for looking into this. I totally understand if this is out of your control and just a limitation of ChartJS.
