### ISSUE TITLE
Reverse Proxy?

### ISSUE THREAD

**Issue by techheaddj** [hargata/lubelog#131]
I am running this in Docker using using Portainer. I have an nginx reverse proxy running to add a certificate to it, but the page is refusing to load. Is there someway I could pull logs to see what's going on with it?

**Comment by hargata** [comment]
I believe you can view the logs in the docker container itself, it outputs the errors to the console/terminal. I'm sorry I've never used Portainer before.

**Comment by hargata** [comment]
@techheaddj I might have some insight for this, I believe that your problem is due to NGINX attempting to serve traffic up to a HTTPS port on the app but Kestrel(the underlying server for LubeLogger), isn't configured to serve up secure connections. So you need to configure https for Kestrel, I've attempted this earlier today with good amount of success, walkthrough below is based on: https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-8.0

To enable HTTPS on this, you need to create a PFX file from the PEM files first using openssl: see this link: 
https://stackoverflow.com/questions/808669/convert-a-cert-pem-certificate-to-a-pfx-certificate

When generating the PFX file, OpenSSL will prompt you for a password, I will use "bob" as an example for the password.
next you're going to need to open and modify your .env file, because you will need to specify the location of the certificate as well as the password. 

You want to add the following lines:
```
ASPNETCORE_Kestrel__Certificates__Default__Password=bob
ASPNETCORE_Kestrel__Certificates__Default__Path=/https/<yourPFXCertificateName>.pfx
ASPNETCORE_URLS=https://+:443;http://+:80
```
First line is the password for the PFX cert, second line is the location within the container about where the cert is, third line is the ports that Kestrel will be listening to for http/https connections, obviously you can change this later.

Next you will need to open up docker-compose.yml(or docker-compose-traefik.yml if you have traefik), and then you will need to bind a volume to it so that LubeLogger can access the pfx cert on launch:
```
    volumes:
      - ~/https/:/https:ro
```

And then just docker-compose up and the server will start serving up HTTPS.

**Comment by ZoXx** [comment]
Can't confirm it. Iam using it two weeks with nginx without any problems.

Maybe wrong configuration in nginx?

**Comment by thehijacker** [comment]
I am also using nginx reverse proxy without any issues. Nothing needed to be done on lubelogger docker-compose file. Just correct nginx configuration:

```
server
{
    listen 443 ssl http2;
    server_name lubelogger.domain.com;

    ssl_certificate /etc/nginx/ssl/acme/domain.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/acme/domain.com/key.pem;
    ssl_dhparam /etc/nginx/ssl/acme/domain.com/dhparams.pem;
    ssl_trusted_certificate /etc/nginx/ssl/acme/domain.com/fullchain.pem;

    location /
    {
        proxy_pass http://192.168.28.53:8289;
        client_max_body_size               50000M;
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_redirect off;
    }
}
```

**Comment by lehmand001** [comment]
cloudflare tunnels do not work either.

**Comment by hargata** [comment]
@lehmand001 I don't have much experience with cloudflare tunnels, but I don't see how this is an app-related issue. The app is served by a web-server underneath, it doesn't matter what you put it behind.
It's most likely a configuration error.

**Comment by hargata** [comment]
Closing this issue since it's a server configuration error and out of scope for this app.

**Comment by ZoXx** [comment]
> cloudflare tunnels do not work either.

+1.

Moved from nginx to cloudflare with tunnel and doesnt work.

**Comment by mathgeniuszach** [comment]
To add some context to this issue as I ran into a similar issue and was able to find a solution. Kestral is a much more touchy server, and so it will error on minor things or header strangeness that other services don't have issues with - this is definitely not something that Lubelogger can change.

I'm running Lubelogger on NixOS under a reverse proxy, and my issue was that by duplicating headers accidentally in my config, Kestral would send back a 400 error with no logs or content. For you to debug, I'd recommend checking the server response to see if it's a 400 error or similar. Look at nginx's access.log or error.log files. Hopefully this can help the next person who runs into something similar.
