### ISSUE TITLE
[BUG] Average MPG Calculation Incorrect

### ISSUE THREAD

**Issue by DoduRH** [hargata/lubelog#132]
I have just setup LubeLogger (decided I wanted to track fuel usage this year) and looked at the MPG on the vehicle report to find it being strangely low.

Fill-ups
![image](https://github.com/hargata/lubelog/assets/43971524/10a3d83d-b9c1-4b2c-8cec-2fd3fca47784)

Vehicle Report
![image](https://github.com/hargata/lubelog/assets/43971524/9b7c53ff-ada7-4f54-89cf-7a77c99cb32d)

This appears to be an issue with the way that the average fuel consumption is calculated, with just 2 items the calculation is 

`sum(all_fuel_economy_numbers)/total_fuel_economies`

This is incorrect as can be seen by the following (toy example)

![image](https://github.com/hargata/lubelog/assets/43971524/06a160bd-7626-49f3-a51f-71713f106553)

I would expect the fuel economy to be `sum(total_miles_done)/sum(total_gallons_filled)`

Ideally there would be a 'starting miles' field so it is obvious that the first tank of fuel was for 281 miles, then do 

$\frac{281 + 559 + 41}{61.78+45.73+0.22} \approx 8.17$

The fill up of 0.22 liters shouldn't be weighted the same as the larger fill ups.

**Comment by hargata** [comment]
You're right, biggest hurdle IMO is calculating the total miles done, I think I can probably get that by taking the max odo reading in the gas records and subtract the smallest odo reading then take that and divide by consumption, that would probably be the easiest way of getting the right MPG, otherwise it's going to include all of the partial fuel ups/missed fuel ups/initial entry where the MPG is zero.

**Comment by DoduRH** [comment]
I think you'd want to skip the ones where the `missed fuel up` flag is true because else more fuel has likely been put into the vehicle vs what is actually recorded (also messing with MPG calculations)

**Comment by hargata** [comment]
right on, I think I've got something, basically the ones where the MPG field is blanked out either due to missed fuel up or partial fuel up or because it's the first entry are going to be excluded first, then whatever remains I'll apply the formula of (maxOdometer - minOdometer) / sum(gallons consumed).

**Comment by hargata** [comment]
kk, I have released some fixes for this, this should be correct now if you'd pull the latest docker image down.

**Comment by hargata** [comment]
Closing this as fuel mileage are now weighed more evenly across the board and not skewed by records where MPG calculation is skipped anymore.
