### ISSUE TITLE
[Feature Request] - Mail Credentials SMTP

### ISSUE THREAD

**Issue by ZoXx** [hargata/lubelog#152]
Hey,

it would be nice,
if you could enter and test your e-mail access data directly in the interface in future.

At the moment there is no way to send e-mails (as reminders), right?

**Comment by hargata** [comment]
@ZoXx Unfortunately I don't think the SMTP credentials should be configured within the app due to it being a security risk. I chose the environment variables method because they can injected during the deployment process via vaults and whatnot. Unlike user creds which can be hashed, SMTP creds would have to be encrypted to be stored and then decrypted to read those values so that the SMTP client can send the email and I don't think this app should be responsible for securing those credentials.

Currently there is no way for emails to be sent for reminders, they are only used exclusively for user registration and password resets.

**Comment by hargata** [comment]
In regards to sending out emails for reminders, I have since added an API endpoint that will automatically pull all vehicle's collaborators' email address and send them reminders based on the urgency. Note that you have to use the Root User's credentials to execute this endpoint.
Example bash script:
```
curl -n -u "rootUser:rootPassword" --location "https://lubelogger.mydomain.com/api/vehicle/reminders/send?urgencies=NotUrgent&urgencies=VeryUrgent&urgencies=Urgent&urgencies=PastDue"
```
You can schedule this to run once a day using a cron job.

This issue will now be closed.

**Comment by ZoXx** [comment]
Hey,

thanks for the quick response.

To be honest, I see less risk if the data is encrypted or hashed directly in the database. Many software solutions work accordingly and there is a direct option to test the settings.

How can e-mail settings currently be stored via variable?

**Comment by hargata** [comment]
@ZoXx so the email settings are stored/injected via environment variables, the provided .env file covers what those variable names need to be. You can inject those variables upon deployment via a secrets vault if you don't want to inject them in plain text. 

SMTP credentials should not be stored by LubeLogger, because it cannot guarantee the security of the credentials. Even if I were to implement an encryption algorithm, it's pretty futile since this is an open source app and the algorithm is available to everyone and it won't measure up to any of the other secrets vaults out there.

Login credentials for users are handled via a one-way hashing algorithm in LubeLogger, which means, that even if someone got ahold of the DB file and try to query the user's password, they cannot reverse it because there is no algorithm to reverse those passwords. Whereas if LubeLogger stores the SMTP credentials and encrypt it, anyone with the db file can easily decrypt the SMTP credentials, which is a major security risk.

Hence, LubeLogger will never store SMTP credentials.

**Comment by ZoXx** [comment]
Got it! That makes sense, thank you very much for the detailed and good explanation!

I have looked at the .env, I will test it!

Many thanks
