### ISSUE TITLE
[Feature Request] Reports and attachments

### ISSUE THREAD

**Issue by Hawkins1212** [hargata/lubelog#159]
I like how clean the Vehicle Maint. Report looks.  I'd like to see if you can build upon it:

1) "Uploaded Documents/Receipts" - So I upload my receipts with my parts/service orders.  It'd be helpful if the Vehicle Maint. Report pulled the receipts/Uploaded docs in chronological order of the services and included in the attachment generated.  It's kind of painful thinking I'd have to go in and pull every doc if I ever wanted to support the service performed

2) Is there a way to have reports generated for each tab.  For example, I am tracking my Fuel purchases and uploading receipts for each of the fuel purchases.  It'd be nice to again have a listing of all the fuel purchases similar to the "Vehicle Maint' Report" that also pulls the uploaded documents.  

Thanks!

**Comment by rtrickett337** [comment]
I definitely like the idea of being able to generate the Vehicle Maintenance Report and have a toggle to select 'include documents' or not. Certainly selling the vehicle, being able to select that option and hit print would make it super easy to hand off all the service history on the vehicle :)

**Comment by hargata** [comment]
@Hawkins1212 @rtrickett337 I was working on this, the biggest roadblock is actually trying to embed the pdf, docx, and xlsx files onto the report itself. I was thinking of a compromise, in which that I would add a second button under the "Vehicle Maintainence Report" button called "Download All Attachments", and what this button will do is that it will retrieve all the attachments in chronological order and download a zip file. So after the consolidated report has been generated and printed, you can then print all of the attachments separately.
Lmk if this will work?

**Comment by Hawkins1212** [comment]
@hargata   I think that is certainly a better alternative than what's there now.  I had kind of the same thoughts as @rtrickett337 as I'd love to be able to print the report and have all the documents there to provide to a potential buyer.  We upload all these documents and having an easy way to sort/pull would be 1000x easier than going to the folder on the "server" (or wherever it's located) and just copy and pasting from that.

If it makes it easier to combine the reports, perhaps make the documentation requirement to be PDF only so we are only dealing with PDF's?  Its easy enough to print doc's and word files to PDF and may make the implementation a bit easier for you?  I am not a programmer so not sure?

Also on your suggestion, I'd be concerned if there are multiple vehicles in the "Garage" that the attachments download you suggest would pull ALL attachments vs. only those associated with that vehicle.

**Comment by Hawkins1212** [comment]
@hargata  as a side note, it'd be nice to have this PDF report printable for most tabs.  For example, printing my fuel logs and fuel receipts would be helpful.   Or even a way to select/include multiple tabs in Vehicle Maint. Report where we can include any tab we please would be a great feature as well.

**Comment by hargata** [comment]
@Hawkins1212 the problem is actually with PDFs or any non-image type files in general. Anyways, the button will only export attachments tied to that vehicle. Here's how it works:
There is now a button here:
![image](https://github.com/hargata/lubelog/assets/155338622/79366fb5-b6a1-4863-92ce-32fa5b39b13b)
When you click on the button, it will prompt you to select which tabs you want the attachments to export from:
![image](https://github.com/hargata/lubelog/assets/155338622/2f3732aa-63b0-42d9-a733-9113ce3c57e0)
It will then retrieve all the attachments, sort it in chronological order, and it will then download a zip file.
Inside the zip file, you will notice that the files are named by numbers, that is the order you want to print those documents in.

As for the export for other tabs, I have added this function in the same dropdown where the CSV export buttons are:
![image](https://github.com/hargata/lubelog/assets/155338622/9a285141-805d-40a8-a9cc-39f95983c463)

When you click on it, it will generate a printer-friendly document that you can print:
![image](https://github.com/hargata/lubelog/assets/155338622/b1bdacca-0dc7-43a9-9d27-9d76137e35fa)

**Comment by Hawkins1212** [comment]
@hargata  I think that looks great and is a great start for now.  Given I don't have a programming background it's hard for me to understand what goes into the development of these features so I am grateful for your time and effort here.  I'll mess around with it on the release and let you know if I have any questions or comments.  I just bought a new vehicle so I am starting fresh with that -- i don't have a lot of entries yet-- however, this type of "software" is exactly what I was looking for so I am glad I found it when i did.  I'll likely start implementing my other vehicles into this soon too.

**Comment by hargata** [comment]
@Hawkins1212 Thank you for the support! 

A lot of roadblocks have to do with proprietary software that makes it prohibitively expensive or difficult to embed those documents onto a web page. 

The free option to embed PDFs is by delegating the responsibility to the web browser the user is using, but most web browsers have their own implementations of a PDF Viewer(i.e.: Google Chrome) where they inject certain stylings such as toolbars, etc onto the PDF viewer itself. While there are workarounds for this(such as Mozilla's PDF.JS), the experience is not consistent across all browsers, which makes it very difficult to maintain. This is an issue that's plagued the tech industry for as long as PDFs existed: https://stackoverflow.com/questions/2104608/hiding-the-toolbars-surrounding-an-embedded-pdf

The free-ish option is to use third party APIs such as the one provided by [Adobe](https://developer.adobe.com/document-services/apis/pdf-embed/) and mis-using [Google's Doc Viewer API](https://issuetracker.google.com/issues/209969101?pli=1).
None of these are good long term solutions since these functionalities are subjected to change by their vendors.

Commercial solutions tend to be the way to go, I work in the tech industry and every year we fork out a good chunk of change to Adobe for a decent PDF solution, but if I were to start investing in commercial solutions for use in LubeLogger then I would be a lot less inclined to keep it free and open-source.
