### ISSUE TITLE
auth error 

### ISSUE THREAD

**Issue by marc115uk** [hargata/lubelog#168]
If I enable Authentication I get the following error throw up in portainer logs every few seconds. If I turn off Authentication enable I dont get any error messages. Any way to resolve this my end? Also I believe I am setting correct environment settings for SMTP but will not send email out   

info: CarCareTracker.Middleware.Authen[12]
      AuthenticationScheme: AuthN was challenged.
info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Cookie is invalid or does not exist.

    environment:
      - LC_ALL=en_GB.UTF8
      - LANG=en_GB.UTF8
      - MailConfig__EmailServer=smtp-mail.outlook.com
      - MailConfig__EmailFrom=my.email@hotmail.com
      - MailConfig__UseSSL=true
      - MailConfig__Port=587
      - MailConfig__Username=my.email@hotmail.com
      - MailConfig__Password=MySuperSecurePassword

**Comment by hargata** [comment]
@marc115uk Unfortunately the auth cannot be resolved completely due to the way auth is handled in the app, it supports cookie-based auth and basic auth via HTTP Requests and when it doesn't see either one of those auth methods it will log an error although it will continue functioning and won't impede your usage.

I've never tried it with an outlook account before, but I know many people have had a lot of success with using Gmail SMTP

**Comment by hargata** [comment]
@marc115uk hey I found a solution for the error logs, just add the following line in your environment variables and you're golden.

`LOGGING__LOGLEVEL__DEFAULT=Error`
