### ISSUE TITLE
Error: average MPG calculated wrong

### ISSUE THREAD

**Issue by straighttalk86** [hargata/lubelog#187]
My max MPG is 39 and min is 21, but the average is showing as 40
![Average wrong](https://github.com/hargata/lubelog/assets/12070445/c5b56ee7-1311-477e-a079-670423434e7e)

**Comment by hargata** [comment]
Is this an older version? Can you see #169 ?It's pretty similar to what you're seeing, I released a fix for it 4 days ago.

**Comment by Abateman121** [comment]
I am on version 1.1.0 and this issue seems to have come back.  I noticed my avg fuel economy went above my max fuel economy after i added my last tank.
![image](https://github.com/hargata/lubelog/assets/83042153/ca56e2ec-0005-4c50-ada2-bc46b45cddd4)

It seems to be related to marking tanks as missed.

https://github.com/hargata/lubelog/assets/83042153/e54aa5d2-4c5e-4c2f-8aae-6dc8bc81cb12

**Comment by hargata** [comment]
@Abateman121 @straighttalk86 
ahh kk, so I figured out why this is going on, but I don't have a good way to fix it.

The way the average fuel mileage is calculated is that it first determines what fuel records need to be calculated, it does this by filtering out the initial fuel record(which has a MPG of 0) and any missed fuel ups, so that only full and partial fuel ups are included in here.

After that, it calculates the difference between the max and min odometer reading in this subset to get the number of distance traveled. It'll then divide the difference by the total amount of gas consumed within this subset.

The problem here is that odometer, like time, is a linear reading, meaning that it only goes up, even if you had missed fuel ups in there, the distance you have traveled is still included in it, but Fuel Consumption is not linear. Fuel consumptions are excluded in the event of missed fuel ups, since we cannot gauge the exact miles traveled.

What I can probably do, is deduct the miles traveled by missed fuel ups. so if you have a missed fuel up and the distance between that and the previous record is 500 miles, it will deduct 500 miles from the total distance traveled. This could probably work in a pinch, but it's still not perfect and will subject the data to being skewed.

**Comment by Abateman121** [comment]
Sorry but it still seems to be having issues. Now the avg is below the min miles

![image](https://github.com/hargata/lubelog/assets/83042153/89a38cba-fd9f-4b0f-9b67-c3ac3718a956)

Have you thought about about just just taking the fill ups where mpg  was calculated and only getting the average of those values?

**Comment by hargata** [comment]
@Abateman121 Can't, because it won't weigh right, see #132

**Comment by straighttalk86** [comment]
Thanks for looking into this.  I deployed the latest changes you made and the average is now between the min and max, so that's good.  For me I would just expect that all the fuel economies from each entry would be summed up and then divided by the total number.  Any null fuel economies would be excluded.
![image](https://github.com/hargata/lubelog/assets/12070445/32e804c7-7ad7-4a87-9b25-c1792dbb72a7)

**Comment by hargata** [comment]
@straighttalk86 Yeap, I updated the average fuel mileage calculation just forgot to post it here, it should now calculate it pretty decently.

**Comment by spcqike** [comment]
i would like to report back, that there still might be some problems with calculations.

i'm on the latest docker image (1.4.0) and just started to input my data
![grafik](https://github.com/user-attachments/assets/e9f71881-5f9a-4536-83c1-9e35f88ea987)

the average is right, min, max and the first datapoint with odometer is wrong.

**Comment by hargata** [comment]
@spcqike 

Make odometer optional:

![image](https://github.com/user-attachments/assets/e0aaab7a-e8d8-425f-9883-4d7fb1827cd1)

![image](https://github.com/user-attachments/assets/343ee870-0e7d-4d28-a1fc-b6ecd4f90e5f)

![image](https://github.com/user-attachments/assets/12fdfbc1-5058-4409-8c16-d41af25fd7f2)

**Comment by hargata** [comment]
@spcqike 
I see, yeah that's going to be tricky if technically the vehicle never has a full fill up. 

I think a good workaround is to change how you look at a full fill up, e.g.: If you never charge your vehicle pass 80% then 80% would be considered a full fill up. I know Tesla's has a user-adjustable charge limit, but that would require you to never adjust the charge limit once it's set.

It's unlikely that LubeLogger would be able to fully cover this use case, because the adjustable charge limit is the equivalent of a variable size fuel tank, which makes it impossible to calculate how much fuel/energy was actually used to cover the distance.

**Comment by spcqike** [comment]
Well, one could also just add up all charges „in The head“ and only add datapoints to lubelogger, when a full charge was made. So instead of 4 partial charges with 20kWh each, one with 80kWh and odometer value. 

It looks like one can also just use the same odemeter value until a full charge was made. This will result in several partial charges without distance (as all have the same odometer) and just one last and full charge

like here 
<img width="667" alt="image" src="https://github.com/user-attachments/assets/a77b211a-4692-4607-918f-dfb567fdaf8c">

Idk why, but I thought lubelogger could just calculate distances and economy based on all given data.
In the picture I have 2 full charges with odometer (first and last) and one partial charge without (second). Do you think it’s possible to calculate distance between full charges with odometer (first and last) and charged energy from last full charge (first row) to previous full charged, so first+second? 

I know, that’s different from how we fill up a petrol car, but I guess it’s the more common way for an E.V. 

Anyway, thank you for this great tool (: I just installed it today and it is really great so far.

I think for now I will combine multiple charges to just one, or just use the same odometer reading again. Whatever is easier to handle (:
