### ISSUE TITLE
Feature Request: Tools

### ISSUE THREAD

**Issue by iotech-fvtt** [hargata/lubelog#271]
Similar to Supplies and Shop Supplies, would like to have ability to track standard and special tools, both tools for specific vehicles and Shop Tools used on multiple vehicles. Fields like description, vendor, cost, image, document, eti/hours

**Comment by hargata** [comment]
@iotech-fvtt 
I've been working on adding the tags feature to supplies and I was wondering if it could potentially cover this use case? You can tag tools separately
![image](https://github.com/hargata/lubelog/assets/155338622/ea72b25c-7534-4816-aa0b-1ecc9affc38d)
and just like the other tabs you can also filter them down on both the Supplies tab.
![image](https://github.com/hargata/lubelog/assets/155338622/99570386-243a-42ee-bb45-6a9a6c68e41d)

It might also cover the use case for #272 since you can easily tag consumables as such and be able to quickly filter / find them when requisitioning for supplies:
![image](https://github.com/hargata/lubelog/assets/155338622/4cfe5ee3-5d8e-4095-b4d9-6e726ab7e5db)

**Comment by iotech-fvtt** [comment]
I think that would work fine, and allow for many more types of objects than
just Consumables/Parts/Tools. I like it!

**Comment by hargata** [comment]
@iotech-fvtt awesome, this is scheduled to be released on Wednesday the 14th.

**Comment by hargata** [comment]
Released today.

**Comment by iotech-fvtt** [comment]
Thank you!
