### ISSUE TITLE
Feature Suggestion: Add Total & Annualized Cost of Ownership Datapoints/Reports

### ISSUE THREAD

**Issue by a2brew** [hargata/lubelog#342]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [X] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [X] I have searched through existing issues.

**Description**

I think it would be very powerful to have the application calculate the total cost of ownership (depreciation, fuel, repairs, maintenance, etc.), which would seem fairly straightforward if you gather the following datapoints:

Add to Vehicle Form:
- Purchase Date
- Purchase Price
- Purchase Mileage
- Purchase Dealership
- Estimated Current Value: (manual $ value)

“ Traded In/Sold? “ Checkbox
- (if Traded In/Sold? Checkbox is checked)
— Sold Date
— Sold Price
— Mileage When Sold
— Sold to:

In my view, once you have these datapoints, you can then add new dashboards/reports that highlight the annualize/total cost of ownership per mile driven, month owned, etc. Both for previous vehicle & currently owned vehicles.

Fantastic work on this app & thanks for all your hard work!

**Platform**
- [X] Docker Image
- [ ] Windows Standalone Executable

**Comment by hargata** [comment]
Hey!
As of 1.2.4, I have added the following two fields at the vehicle level: Purchased Date and Sold Date
![image](https://github.com/hargata/lubelog/assets/155338622/078d12aa-627a-48f5-8944-4abe929a472b)

These two data points will be used to calculate the length of ownership.
![image](https://github.com/hargata/lubelog/assets/155338622/ce1c48a1-c5f0-422f-8ae4-609c73e4c82f)

And if you look closely at the screenshot above, you will also notice the total distance traveled and the total cost(excl. fuel) per distance unit along with the total fuel cost per distance unit

Along with those data points above, you can also add extra fields at the vehicle level.

Watch this video walkthrough for more info:
https://www.youtube.com/watch?v=fV0DdYaoajU

A note on Depreciation expense calculation, it's not going to be implemented in LubeLogger for a few reasons but primarily because it's out of scope. LubeLogger primarily tracks tangible expenses such as services, fuel, etc, and depreciation is intangible and highly subjective to the current market value of the vehicle which can potentially skew the expenses. It is however, not terribly difficult to calculate it yourself using the data points that LubeLogger already tracks such as the length of ownership and distance traveled. 

The secondary reason is because LubeLogger is not designed to replace accounting suites / asset valuation software. I have worked on accounting software in my career and I am aware that implementing any sort of depreciation mechanism is going to potentially open up a can of worms. It is not as simple as (purchase price - sold price) / length of ownership
