### ISSUE TITLE
[FEATURE REQUEST] enter milage in kilometers, but still calculate MPG

### ISSUE THREAD

**Issue by affiliate7473** [hargata/lubelog#364]
My motorcycle odometer is in kilometers (km), European spec motorcycle sold in UK, but I still want MPG calculated on my fueling. 

I'm currently converting the km to miles before entering in lubelogger. 

Is there any chance you can add km as an entry option on the odo, with the neccesary conversions happening to calc MPG?

**Comment by mdlopresti** [comment]
I second this, I own both standard American cars, and I just got a Kei truck.  Being able to set the units on either the odometer or the vehicle would be very useful

**Comment by hargata** [comment]
I'm trying to come up with the best way of implementing this. I currently have the following each with various pros and cons:

- A button right beside the Odometer field that will convert whatever is in the field between miles and km depending on the user's default setting. Pros: easy to implement, Cons: you have to press the button every time you enter a record to convert it from miles to km or km to miles.

- A switch in the Vehicle details page that states that it will use the opposite of the user's settings. Pros: you can enter the odometer number in km or miles depending on what the vehicle uses and it will do the conversion automatically in the backend. Cons: all the existing records for that vehicle will now be converted, which means if you have been converting from km to miles it will divide it by 1.6 a second time and result in incorrect data. Longer implementation time. Additional complexity for a majority of users since this is kind of an edge case.

I'll try to experiment with either of these options and see what comes out of it.

**Comment by hargata** [comment]
@affiliate7473 @mdlopresti 
Alright, I've tried out a few ideas but I think this is the best one I can come up with, lmk what y'all think.

At the vehicle level, there's going to be this new switch called Odometer Adjustments:

![image](https://github.com/hargata/lubelog/assets/155338622/03cd7d7c-baf4-4738-8711-b13e4a6caffc)

When it's enabled, these two new fields will be visible:

![image](https://github.com/hargata/lubelog/assets/155338622/764ce10d-ec36-4d52-b89c-7136893f0b11)

Odometer Multiplier is basically the multiplier of the vehicle's odometer units to your user settings.
So in y'all's use cases where "miles" is set as the default distance unit but your vehicle uses kilometers, you can input 0.621 in the Odometer Multiplier. It is a multiplication operation, so when you go and **add** a new record (odometer/service/repair/upgrade/fuel/etc), you can input kilometers in the odometer field and it will automatically multiply it by 0.621 before the record is saved. **Note that this conversion ONLY happens when ADDING new records, editing existing records will not have this conversion.**

Odometer Difference doesn't really apply to your use case here, but it's mainly for vehicles with swapped dash clusters and hence the odometer reading no longer reflects the actual mileage. E.g.: your dash cluster broke when the odometer was stuck at 200000 miles and you replace it with a dash cluster where the odometer only reads 15000, your odometer reading now has a difference of 185000, so you will input 185000 into the Odometer Difference field. The next time you go and add a new record you just have to input whatever the new dash cluster is displaying e.g.: 17500 and it will automatically add 185000 to 17500 while the record is being saved.

Here I have an example for a R34 Skyline GTR where the odometer is in kilometers, so here's how I will set it up:

![image](https://github.com/hargata/lubelog/assets/155338622/0f2d73f1-ee8e-419b-b202-5a08c51eb061)

When I add a new odometer record at 15000 KM, I will just input it as 15000:

![image](https://github.com/hargata/lubelog/assets/155338622/19a1a0f5-6d47-4b71-8e86-8a84e193fe8b)

Once I click the "Add Odometer Record" button, it will automatically convert 15000 KM to 9315 MILES

![image](https://github.com/hargata/lubelog/assets/155338622/a756b7d5-bed1-4f3b-ad02-121c683d5513)

The conversion is not perfect due to rounding errors, but this is about as good I can get it to work.

Let me know what y'all think, if all goes well I can get this released this Sunday 03/17

**Comment by mdlopresti** [comment]
That works for me. I like the one-time setting nature of it, for sure. I'll need to do a one-time update of editing old entries, but the bulk edit options make that easy.

**Comment by hargata** [comment]
@mdlopresti I'll do ya one better, for the existing records, you can just select them, right click, and "Adjust Odometer"

![image](https://github.com/hargata/lubelog/assets/155338622/d750489d-151e-41f9-b135-45fa096d121a)

and this will apply the odometer adjustments to the selected existing records.

**Comment by hargata** [comment]
@mdlopresti @affiliate7473 this is now released with 1.2.7
