### ISSUE TITLE
[Feature Request] Vehicle Maintenance Report Customization

### ISSUE THREAD

**Issue by Hawkins1212** [hargata/lubelog#375]
First of all, love what you are doing with the product.  It really was exactly what I needed and was looking for when I purchased a new vehicle in Dec 2023.  And I appreciate you taking input from the community on prospective updates. I do have a couple feature requests:

1)  I wanted to inquire on the "Vehicle Maintenance Report" ("VMR") and whether customizations are allowed.  When I pull the VMR, it appears that the "Type" column pulls in Service but does not pull in other expense types.  I'll caveat this and say I've only added "Service" and "Fuel" so I may not have good exposure to everything that would be included in the report.  What I think would be beneficial is if you allow settings that allow us to customize which expense types would be pulled into this report.  For example, I would love to have this report be generated for only Fuel without service, etc.  If we could add/remove expense types, I think this would make this report much more useful.  Note that I understand I can pull a CSV with all of my gas purchases; however, I think your VMR format is clean and I like it and would rather present that to someone in a clean way vs. a CSV.  

2)  Documents -  Currently when I add documents such as Fuel Receipts, it appears the program converts the file names of these documents to "0", "1", "2", etc.   I was one that suggested the ability to pull all documents a month or so ago and very glad you added that feature.  The problem I have is one would have to match up the document types to the expense entries which may prove to be difficult if there are many documents.  Would it be possible to customize the "file name" of the documents when placed into the zip file to be something like   "Type -- Date" or something to that affect.  Or even if it could maintain our original file names, that would be more helpful.  By way of example, I have a Fuel entry on 1/10/2024  and uploaded the receipt with the file name "2024 - 01 - 10 Receipt".  When I pull the documents zip file, the program converts this document name to "0.pdf".  It would be much more useful if the program either converts to name to something like "FUEL - 01-10-2024" or maybe "FUEL - 2024-01-10" so that way it is easy to sort and match up the document with the expense.  If that's not possible, even maintaining the file name of the document I put in there would be more helpful than renaming it "0" because then I could institute a naming system prior to uploading documents to ensure the attachments are sortable to my liking.

Thanks again for your help!

**Comment by hargata** [comment]
For Item 1, I can do a prompt similar to the attachments export feature where the user can select which types of expenses they'd like to see in the VMR; however, I don't think Fuel Records will make it into the report anytime soon due to the amount of additional columns needed to fully display the data, instead, have you tried the "Print" functionality found in the individual tabs?

![image](https://github.com/hargata/lubelog/assets/155338622/1a3a5582-f481-4029-be5f-01ed434b920f)

![image](https://github.com/hargata/lubelog/assets/155338622/3564eb53-7259-4b44-b799-5d3718b0b8bb)

For Item 2, I'll look into categorizing the attachments into subfolders and then name them in this format <number to indicate chronological order>_<Date Of Record>_<Original File Name>

**Comment by hargata** [comment]
Item 2 is released in 1.2.6.

Watch: https://youtu.be/x4xY-YQN-5w?si=YH4Pi7i8xh5uJp-o&t=337

Item 1 was really hard to justify because users can already export individual tabs via the Print functionality so it didn't make a lot of sense to implement an additional selection dialog on the Consolidated Report.
