### ISSUE TITLE
[Feature Request] Support for Electric and Plug-In Hybrid vehicules

### ISSUE THREAD

**Issue by skylarkbe** [hargata/lubelog#386]
All is in the title

A new energy type ( kWh ) should be added to support EV and PHEV vehicules

**Comment by hargata** [comment]
this is already supported.
just check "Electric Vehicle" in the Vehicle details form and it will show kWh instead of gas units.

**Comment by skylarkbe** [comment]
Thanks for the feedback. What about the Plug-In hybrids ?

**Comment by hargata** [comment]
@skylarkbe PHEV is tricky to support because it will require both units and LL only supports one consumption unit per vehicle, but it does support multiple fuel types if you tag the fuel records. It's very unlikely that we will implement support for PHEVs because it can complicate the record adding process for the majority of vehicles that are not PHEVs.

tbh, it's just a label that displays kWh in place of gallons / liters. I would just pick one unit whether it's electric or regular fuel, and then use the tagging functionality to filter the other out.
