### ISSUE TITLE
[Feature Request] Username case insensitive

### ISSUE THREAD

**Issue by Luna-za-tuna** [hargata/lubelog#395]
Just want the username to be case insensitive so that User and user would both work. Its a small thing, but it gets annoying since mobile tends to automatically capitalize things.

**Comment by hargata** [comment]
The username for non-root users are already case-insensitive by default. You can try this on the demo site by logging in with username tEsT and password 1234 and it will still log you right in.

For root users on the other hand, we can't do case-insensitive because the hash will not match otherwise. In our documentation, we encourage users to set up a secondary account and mark the second account as an Admin user even if they are the only user in the system. see [here](https://docs.lubelogger.com/Authentication#rootsuper-user)

The username for root users will remain case-sensitive because we hash both username and password of the root user to ensure highest level of security, see [Technical Docs](https://docs.lubelogger.com/Technical%20Docs#user-credentials)

**Comment by Luna-za-tuna** [comment]
Thank you for the detailed write up and links. I appreciate the thought put into it the docs.
