### ISSUE TITLE
[Feature Request] Disable Login When OIDC configured

### ISSUE THREAD

**Issue by dregini** [hargata/lubelog#416]
Hi,
I just set up lubelog and i find it awesome!!
I managed to configure the OIDC login with Keycloak, but it would be nice if it was possible to disable the standard login prompt and when a user is not logged in instead of serving the login page automatically initiate the OIDC login flow

Thanks

**Comment by hargata** [comment]
I've looked into this, but since OpenID doesn't have Single Sign **Out** implementation, it means that if auto login via SSO is enabled then the user can potentially be stuck in a loop when they try to sign out from LubeLogger, since the sign out process works like this:

Sign Out -> Clear cookies / cache / etc -> Redirects user to login screen

But if auto redirect to OIDC is enabled, then the flow becomes like this:

Sign Out -> Clear cookies / cache / etc -> Redirects user to OIDC Login -> User stays logged in if user was already authenticated in OIDC.

**Comment by redge76** [comment]
If you are using keycloak, I guess you are also using some kind of reverse proxy.
So instead of this feature you could request LL to just trust the user sent in an http header by the proxy and let the proxy deal with the authentication stuff.
see "authResponseHeaders" for traefik https://doc.traefik.io/traefik/middlewares/http/forwardauth/
or headerField for basicauth https://doc.traefik.io/traefik/middlewares/http/basicauth/
Cf-Access-Authenticated-User-Email for cloudflare (https://community.cloudflare.com/t/cloudflare-access-headers/181674)
for caddy https://stackoverflow.com/questions/73213698/get-user-id-from-caddy-and-cherrypy-basic-auth

On LL side you have to configure which header to trust and how to match LL user with this header. And voila ...

Best way to configure authentication for small projects. You configure it once at proxy level and then every compatible app is easy to configure.
guacamole https://guacamole.apache.org/doc/gug/header-auth.html
home assistant https://github.com/BeryJu/hass-auth-header
...

**Comment by hargata** [comment]
Added in 1.2.8:

Just have to inject the following environment variables and LubeLogger will auto-initiate the OIDC login flow when the user navigates to it. Note that you have to provide a Log Out URL for your OIDC provider so that the user doesn't get stuck in a loop when they attempt to Log Out from LubeLogger

```
OpenIDConfig__DisableRegularLogin=true/false(default: false) - auto re-direct user to OIDC login.
OpenIDConfig__LogOutURL=Log Out URL for OIDC Provider, required if DisableRegularLogin=true.
```

**Comment by dregini** [comment]
wooooow awesome!! 
it works perfectly!
super thank you!!
