### ISSUE TITLE
[Feature Request] History Print View

### ISSUE THREAD

**Issue by bradyemerson** [hargata/lubelog#42]
Would be awesome to be able to print a consolidated view of the service, repairs, upgrades that have been made to the vehicle. Sort of like a CarFax history section.

**Comment by hargata** [comment]
this is currently being worked on :)

**Comment by hargata** [comment]
This is now ready for test if you pull the latest docker image down, navigate to the Reports tab and Press the "Generate and Print Vehicle Maintenance Record" button. The reason why it gets sent to printing is because

1. It can take quite a long time to generate
2. The amount of elements on the page would be pretty huge and it can potentially slow the page down.
3. Sending it to print means you get to Print it as PDF and keep for your own records.

**Comment by hargata** [comment]
Feature delivered, closed.
