### ISSUE TITLE
[Feature Request] Reminders - Extra Fields

### ISSUE THREAD

**Issue by joshtbernstein** [hargata/lubelog#447]
Thank you for adding the tags to the reminders. Is it possible to please add Extra Fields as well?

**Comment by hargata** [comment]
can I ask what's the use case for extra fields in Reminders? 

It's pretty tricky to implement features for Reminders in general because that page has so much interactivity and it's the primary reason why it has no CSV Import/Export function, no sorting, and no options to hide/show columns.

If the use case is compelling enough with no workarounds(i.e. storing the data in the Notes field), I might consider re-designing the page sometime down the road.

**Comment by joshtbernstein** [comment]
Got it. I'm looking to group my service reminders by service type. The service types are an OEM thing (German of course).

I'm now using tags to organize my service reminders by area of the car (Undercarriage, Engine Compartment, etc), but it's a lot of tags if I also use them for service type. Now that I think about it though, extra fields won't really work for this since there's multiple service types a reminder could be apart of.

I'm not sure if you have any thoughts on a better way to do this or if I should just stick with tags.

**Comment by hargata** [comment]
Tags will probably be your best bet, tho I fully understand that the ability to only select one tag at a time is pretty limiting, let me look into adding the ability to select multiple tags.

**Comment by joshtbernstein** [comment]
Sounds good. Thanks!
