### ISSUE TITLE
Can not add supplies and reminder to existing repair record

### ISSUE THREAD

**Issue by chris1284** [hargata/lubelog#454]
- [x ] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x ] I have searched through existing issues.

**Description**
It is only possible to add supplies / parts and reminders to new repairs (input mask new repair).
If you like to add parts / supplies after creating a repair, the 2 options for supply and reminder are missing.
If you choose supplies, the price per unit is shown with 3 decimal numbers behind the comma
The supply requisition history shows old descriptions after editing repair description.

**Platform**
- [x ] Docker Image  - LubeLogger Version 1.2.9

**Comment by aidan-gibson** [comment]
I heavily agree with this; ie I am currently replacing my clutch slave cylinder, but the part I received was DOA and is being returned, so I'm using a different replacement part. Kinda sucks that I have to delete the job to add a different supply part.

**Comment by aidan-gibson** [comment]
In general this really feels like a no-brainer; I have lots of planned jobs I would like to add to the organizer I don't have the supplies for yet

**Comment by hargata** [comment]
@aidan-gibson 

> feels like a no-brainer

If this was as straightforward to implement as you put it we would've implemented it months ago, but due to certain design decisions it wasn't as straightforward/easy you'd think.

The fact that we kept this issue open instead of closing it means that we'll get to it eventually, just don't have a whole lot of time to dedicate to this right now since we only work on this project in our spare time.

If you like, you can open up your wallet and fund this feature :)

**Comment by hargata** [comment]
Next Release:

![addsuppliestoexisting](https://github.com/user-attachments/assets/1cd1edf7-a3cd-405a-8059-336183e3d06f)

**Comment by aidan-gibson** [comment]
Thank you!!

**Comment by hargata** [comment]
Released.
