### ISSUE TITLE
[Feature Request] Vehicle-specific reminder urgency thresholds

### ISSUE THREAD

**Issue by barstown** [hargata/lubelog#477]
**Checklist**
- [X ] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [X ] I have searched through existing issues.

**Description**
From Issue #124:
> The reminder becomes "Very Urgent" when it has less than 7 days to due date or less than 50 miles to the target odometer reading, so you'd have to intentionally ignore it for it to become past due.

Reminders change their urgency status at set intervals that are not user configurable. This seems to work okay for reminders that have longer intervals, but for reminders that have a short interval time those tasks are perpetually "very urgent" or "urgent."

As an example, I set up a farm tractor as a vehicle on your live demo website and created a reminder entry for "Grease fittings." My tractor requires that I grease them every 10 hours. When I create a service entry or select the "done" button for that item it resets and updates the hours correctly, but the task remains "very urgent." For this specific task, I'd probably set my urgent state to 5 hours and the very urgent state to 8 hours or so.

Another example, I created a vehicle for my lawn mower which recommends oil changes every 50 hours or annually. Same concept here, I had a task that repeated after 1 year or 50 hours, and when I added the service entry for it the fields all updated appropriately, but the reminder reset back to an "urgent" state. For this specific task, I'd probably set my urgent state to 35 hours and the very urgent state to 45 hours since I don't accrue hours on my mower all that fast.

If you made Reminder urgency configurable per entry, that'd help get some of these short tasks out of the higher urgency state. Alternatively, maybe changing how it determines that state to be percentage based on the interval time could be an improvement? At 50% past the interval time it becomes urgent and at 80% it becomes very urgent? I'm flexible here, but I've seen that you said the Reminders page has a lot of interaction with other pieces so I'm not sure how feasible this is.

**Comment by hargata** [comment]
Not at a per entry level, but the urgency thresholds are configurable app-wide. Available as of 1.2.5, please #366

**Comment by barstown** [comment]
I had missed that, and that looks really helpful. I don't see that on the demo site, but I recognize that certain things may be disabled there.

Would you consider making the reminder thresholds be vehicle-specific in the future? That's still going to present a similar issue, but now the opposite. If I tailor it for my equipment with frequent maintenance items, my truck's reminder urgency thresholds will be skewed now as well.

**Comment by hargata** [comment]
Sure.

**Comment by hargata** [comment]
@barstown Hey, just wanted to let you know that the scope of this feature is superseded by Reminder-specific urgency thresholds, so instead of setting the custom urgency thresholds at the Vehicle level, you will be able to set the urgency thresholds at each Reminder level in the next release.

For more info, please see #609

**Comment by hargata** [comment]
Released in 1.3.7:

![image](https://github.com/user-attachments/assets/ea058b88-4428-42ec-a88c-628a0ddf3664)

**Comment by augmentedagent** [comment]
It would be valuable to me to show the amount of time/miles remaining until the due date/mileage. Could this be added to the reminder screen?  

In my current tracking spreadsheet, on the dashboard, for each vehicle I have various metrics
 - Total miles currently on tire 1, tire 2, tire 3, tire 4
 - Miles since last rotation
 - Miles since last oil change

This allows me at a glance to see how close I am to needing to do service on certain things.

With Lubelogger's reminder feature, this could be handled in the reverse from the reminders screen if the delta was shown on the reminder.
