### ISSUE TITLE
[Feature request] Ability to re-order Notes (and export/import)

### ISSUE THREAD

**Issue by alternativesurfer** [hargata/lubelog#523]
![image](https://github.com/hargata/lubelog/assets/10135929/8ac2d6a8-2105-475f-9962-8f99758009bf)

I would love to be able to move these around, more than just Pinning lets me do.
Same goes for export/importing notes.

**Comment by hargata** [comment]
Next release:

Notes are sorted in ascending order by their description after their pinned status. Pinned notes will still be displayed before unpinned notes, both groups are sorted separately. Appending a number in front of the notes description would be the best way to sort it, otherwise it will be sorted alphabetically.

See gif:

![orderednotes](https://github.com/user-attachments/assets/de6daa64-f3c6-448f-a571-c10ad1969b76)

**Comment by hargata** [comment]
As for importing/exporting notes, that wouldn't be super feasible as a CSV export due to the potential large sizes of the Note contents, however, you can duplicate the notes across other vehicles:

![duplicatenotes](https://github.com/user-attachments/assets/86cbbc31-be24-445e-bf8e-10e7ee7fa911)

**Comment by hargata** [comment]
Released.
