### ISSUE TITLE
[Feature Request] Export / Import reminders for use on other vehicles

### ISSUE THREAD

**Issue by alternativesurfer** [hargata/lubelog#526]
Similar as to how Service Records/Repairs/etc can be exported/imported.

**Comment by alternativesurfer** [comment]
Please!

I dupe many reminders across vehicles when creating maintenance schedules and it takes forever recreating them all.
=(

**Comment by Corza** [comment]
I second this, I'm trying to transfer across from another platform, importing via CSV would be amazing!

**Comment by rougeSE** [comment]
Yes, I would find this amazing as well.

**Comment by hargata** [comment]
Due to the complexity of the reminder object it's not super feasible to add CSV export/import function for it, but on the next release there will be a function to duplicate records(including reminders) to different vehicles which should fulfill your use case.

![duplicaterecords](https://github.com/user-attachments/assets/b52af52a-3380-4515-abc6-f22e6533e4c3)

**Comment by hargata** [comment]
Released
