### ISSUE TITLE
Increase max file size for uploaded documents?

### ISSUE THREAD

**Issue by alternativesurfer** [hargata/lubelog#536]
I have a few service manuals I'd like to store in LubeLogger but they are each a few hundred MB PDFs.
Is there any way to adjust the max uploaded file size?
![image](https://github.com/hargata/lubelog/assets/10135929/6e1f55fd-5697-43e5-a54a-c962df582205)

**Comment by hargata** [comment]
There is no max file size limit past version 1.1.3, the only thing limiting your file upload is probably a reverse proxy like NGINX.

The label is there and is user-customizable via a translation file. You can track down the exact key in en_US.json and change 28.6 MB to whatever you set the file upload size limit to be.

**Comment by adyanth** [comment]
Is this really removed now? I still see this limit on 1.4.3. Also, it does not let me select video files (even if they are under 28.6MB)

<img width="308" alt="Screenshot 2025-01-11 at 10 16 28 PM" src="https://github.com/user-attachments/assets/6e63cf88-365e-47ea-b3a8-7e30ea53cb10" />
<img width="267" alt="Screenshot 2025-01-11 at 10 16 48 PM" src="https://github.com/user-attachments/assets/aeafbbc3-f84a-4e9a-a684-661c21807a7d" />

**Comment by hargata** [comment]
@adyanth it is fully removed. When we removed the file size upload limit, we decided to keep the label in place as it is user customizable. Even tho the app might not have an upload limit, there can still be a limit enforced by the reverse proxy. The label is simply there so that the admin can modify the label and inform the user.

Example:

![image](https://github.com/user-attachments/assets/ffc2b065-6a4c-4f9e-9616-33b3c64a8eb2)

Regarding uploading video files, please read the docs: https://docs.lubelogger.com/Advanced/Technical%20Docs#default-allowed-file-formats
