### ISSUE TITLE
[Feature Request] Dashboard metrics as data tables

### ISSUE THREAD

**Issue by alexsaagi** [hargata/lubelog#551]
For years I have maintained a similar data structure for manual spreadsheets. One of the outputs I miss with LubeLogger is the ability to see cost breakdowns as simple numbers in a table. Let me provide an example of my old spreadsheet for context:
<img width="1237" alt="image" src="https://github.com/hargata/lubelog/assets/128265882/a178b5f9-fd32-4e0e-953e-1f1d8936b1f0">

To adapt the key info from this to LubeLogger I'd suggest a table like this: 
<img width="877" alt="image" src="https://github.com/hargata/lubelog/assets/128265882/9eaaa277-1317-42d2-a115-484720ab2f61">

The end goal being to capture the true cost of vehicle ownership from the data being collected, both in terms of per km (distance driven) and time (months/years). 

We would still be missing some estimate of future scrap value at a certain time to establish estimates for depreciation (you can see this in my spreadsheet example) but I'd consider that a secondary concern.

**Comment by hargata** [comment]
@alexsaagi will be included in the next release.

Clicking on the pie chart will bring up this data table:
![image](https://github.com/user-attachments/assets/b9c5c981-06ab-4037-a15f-787cda10f5cb)

Instead of Monthly cost, I opted for days because it's a lot easier/cheaper to calculate the number of days between two dates than the number of months. The number of days reflects the days of ownership for a specific vehicle. If purchase and sold date are both provided then that is what will be used. If only purchase date is provided then it will calculate the number of days between the current date and the purchase date. 
Otherwise, it will fall back to the earliest record(e.g.: first service/repair/upgrade/fuel/odometer/tax records) to establish the initial date of ownership and today's date to establish the length of ownership, this isn't the most ideal way as it's only an approximation of length of ownership so it's highly recommended that users set the purchase date in the Vehicle details itself.

Number of miles driven is based on the min odometer reading and max odometer reading of all records, unless a year is selected from the dropdown instead of All Time, then it will use the min and max odometer reading of records within that year ONLY. This allows the user to narrow down the ownership costs for a particular year instead of over time.

 This data table shows the following:
Cost Per Day - The total cost over the ownership length of the vehicle.
Cost Per Mile - The total cost over the miles driven during the life of the vehicle OR the year selected.
Total Cost - self-explanatory
