### ISSUE TITLE
[Feature Request] Add tab for Cleaning/Washes

### ISSUE THREAD

**Issue by Hawkins1212** [hargata/lubelog#58]
Since Cleaning, Car Washes, Details, etc. don't fit any of the categories provided, might be good to add a tab for this to track cleaning costs.

**Comment by hargata** [comment]
I originally intended for the "Tax" tab to encompass all costs related to the vehicle that doesn't tie into the odometer reading, so registration, insurance, etc will all fall under there. I renamed it to tax because that is what most people associate those costs as. Maybe you can call it "Clean Car Tax" and add the entry in the tax tab.
