### ISSUE TITLE
[Feature Request] Additional Fields enter data via API

### ISSUE THREAD

**Issue by T00ManySecrets** [hargata/lubelog#588]
I absolutely love the additional fields. You can do a lot of stuff. It would be nice if you could enter data into those fields via API. 
The possibilities are endless. For example GPS data and then when entering lets say odometer data you have GPS coordinates field and you can mark where you ended your trip with a app that uses the API.

**Comment by hargata** [comment]
In 1.3.6(next release), you will be able to add extra fields by adding the following params to your API request:
`extrafields[index][name]` and `extrafields[index][value]`

So for your first extra field it will be `extrafield[0][Extra Field Name]` and then `extrafield[0][Extra Field Value]` then for the second extra field it will be `extrafield[1][Extra Field Name]` and then `extrafield[1][Extra Field Value]`

Such as:
![image](https://github.com/user-attachments/assets/6b445f23-0d17-45d8-ae4a-6f0f0604a798)

Note that you will first need to have the Extra Field name configured for the record type in the Settings page otherwise it won't show up in the record.

Once added, it will appear like so:

![image](https://github.com/user-attachments/assets/7cc29c47-7084-446b-aae4-19046ba1469e)

**Comment by hargata** [comment]
Released

**Comment by T00ManySecrets** [comment]
Love it!!
