### ISSUE TITLE
[Feature Request] SimplyAuto CSV Import

### ISSUE THREAD

**Issue by helio4k** [hargata/lubelog#60]
[SimplyAuto CSV example.csv](https://github.com/hargata/lubelog/files/13904882/SimplyAuto.CSV.example.csv)

**Comment by tetra-archos** [comment]
An Export would also be nice for transferring vehicles between users, ie. I sold a car to a family member on my instance.

**Comment by JcMinarro** [comment]
There are for `.cvs` files that would need to be considered for importing from SimplyAuto.
[Here](https://simplyauto.app/importguide.php), on their import guide, they detail the content of every file

**Comment by hargata** [comment]
@JcMinarro can SimplyAuto export the CSV files separately or is it one big consolidated CSV?

**Comment by hargata** [comment]
It seems like SimplyAuto consolidates all of its records into the Fuel_Log export, and there is no way we're going to even try to support splitting the records out based on its type because that can cause potential issues with importing from other sources; however, I have mapped the columns to what SimplyAuto would export, based on both the documentation and the attached CSV export in the original post.

There is a minor issue with both "qty" and "consumption" columns both being present, but as long as one of the columns is present it will use either, if both columns are present it will always use consumption.

It is up to the user to separate out the fuel records from services/etc, we're not going to separate it out for them.

![image](https://github.com/user-attachments/assets/45bb281f-29ca-4047-81e3-2d3eb3028bb6)

**Comment by hargata** [comment]
@JcMinarro there are 4 files, but Service Records are consolidated into the same file as Fuel Records within the Fuel_Log.csv

![image](https://github.com/user-attachments/assets/87d9dcb8-7788-43ac-80ff-5aa0f22f5669)

LubeLogger isn't going to check the Record Type and determine whether that record should go into Service Records or Fuel.

You will have to separate it into two files, one for Service Records and one for Fuel Records.

**Comment by JcMinarro** [comment]
Ok. I see.
I didn't read/check the `.csv` structure details, but it looks fine. We will need to split the `fuel_log` into 3 different files before to import, Fuel, Services and Expensive, and then importing them on the proper section within Lubelogger.

**Comment by hargata** [comment]
Yeap!

**Comment by hargata** [comment]
Released.
