### ISSUE TITLE
[Feat Request] PWA Support

### ISSUE THREAD

**Issue by edersong** [hargata/lubelog#61]
~90% of data is input when we are out, so PWA Support to be able to better responsive from a mobile phone.

**Comment by hargata** [comment]
PWA meaning just the making so that it can be accessed via a shortcut and have the right name, icon, etc.? I have a feature branch for that right now, but if you're asking for the ability to cache/defer operations when there's no cell signal that is going to take significantly more effort. Right now I have tested the pwa manifest on an iPhone and it works.

**Comment by edersong** [comment]
Cool, it could be enough.
A better and responsive UI for phones will be good.

**Comment by hargata** [comment]
kk, that is added and released. It's got good enough Mobile/Small screen support, but the app relies on horizontal spanning grid to display a majority of its data and it is pretty challenging to optimize horizontal scrolling on mobile.
