### ISSUE TITLE
[feature request] Please build this app for desktop usage on Linux and macOS

### ISSUE THREAD

**Issue by mengineering** [hargata/lubelog#623]
**Description**
Setup and running the app is already easy, but recalling it each time through Docker is a pain for a non technical user.
If you can provide a standalone executable such as Windows' for MacOS and Linux users it would be fantastic!
There's no app easy like this out there!

Thanks for your fantastic job!

**Comment by hargata** [comment]
There is already a standalone Linux executable in the release section.

We're not likely to release an executable for MacOS because of the notarization requirement, BUT we do have a tutorial on how to build it yourself

Please see this documentation on how to build it on MacOS, we even have a video walkthrough for it:

https://docs.lubelogger.com/Misc/LubeLogger%20Builder

**Comment by tveyben** [comment]
I have just followed that good guide and successfully build the app for OSX - great!

I did wonder about the OS X 12.x+ requirement, but as I can see it resembles the dotnet 8.x requirements I am guessing that there is a dotnet 8 dependency (thus it will not be possible to build it for older versions of OSX, those that can run dotnet 6.x but not 8.x).


Is that a  correct assumption - or - will is it possible to build this for OSX < 12 (meaning OSX with dotnet 6.x).
