### ISSUE TITLE
[Feature Request] Integrate translations into the release

### ISSUE THREAD

**Issue by steffenrapp** [hargata/lubelog#645]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

Right now if you don't want to use English as your language you have to go to https://github.com/hargata/lubelog_translations find your translation (if it exists), download it and upload it in LubeLogger. This works quite fine but once the translations get updated you have to repeat these steps over and over again.
It would be nice if all of the official translations would be integrated directly into the container with every release so you're always up to date and have all of them available at any time.

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**

**Comment by hargata** [comment]
Thanks for the suggestion, unfortunately this isn't something we'll be pursuing, for the following reasons:

1. We can't guarantee the translations are up to date with the current release
2. We can't guarantee that the translations are accurate
3. Users have different opinions about how certain things should be worded

Explanation:

1. If we tie the translations into a specific version, we will have to wait for all the contributors to translate any updated/new words before we can release, and this project simply doesn't have a well-coordinated/dedicated group of community contributors for that yet.

2. On top of that, if there is a typo or grammar mistake that slipped through the cracks, users will have to wait till the next release for the changes to be applied, which can take weeks or months.

3. Due to regional/cultural differences, users will disagree over how certain phrases should be worded. De-coupling the translation from the release means that the user can download a translation(if it exists) in their own language, modify the wording and then upload the modified version into their instance of LubeLogger.

1 and 2 are primarily logistical issues which can be mitigated if we get a dedicated group of translators/contributors. 3 is pretty much impossible to mitigate, if we roll the translations into the primary repo we will most certainly get a bunch of issues in this repo to fix/update translations, which we can't help with because we(the primary maintainers) are monolingual Americans.

Translations are community driven, hence we believe it's best that it is de-coupled in a separate repository where people are free to contribute and modify.

Regards.

**Comment by steffenrapp** [comment]
@hargata Thank you for your detailled response. I understand your concerns.
On the other side it seems to be common practice in all of the Open source projects I know to include all of the translstions into the release nevermind if they are complete or perfect. As long as the fallback language is English for missing translations you can still understand everything.
Also, I don't think many people will make a custom translation just for themselves. They might just use what they get but the option to do so doesn't need to be removed.
Maybe you can think about it again.

**Comment by kgraefe** [comment]
With Watchtower the LubeLogger docker container is updated automatically on my system. However, for the translations I have to manually watch the translation repository and manually update the language file. You're putting the burden on every single (non-English) administrator. I'd be happy to accept occasional typos and can very well wait for next release. After all, it's the same situation for the English language file, no?

> If we tie the translations into a specific version, we will have to wait for all the contributors to translate any updated/new words before we can release, and this project simply doesn't have a well-coordinated/dedicated group of community contributors for that yet.

Normally you'd have a translation phase for each release (except urgent security releases). 

> Due to regional/cultural differences, users will disagree over how certain phrases should be worded. De-coupling the translation from the release means that the user can download a translation(if it exists) in their own language, modify the wording and then upload the modified version into their instance of LubeLogger.

There are different language codes for different regions, e.g.: you ship `en_US` but there is also `en_GB`. The same exists for German: `de_DE` (Germany), `de_AT` (Austria) or `de_CH` (Switzerland). So I do think this is a solved problem.

**Comment by hargata** [comment]
I've thought about this and decided to reopen this. How about a compromise?

In the next release, you will be able to download translations from within the app itself. It will always download the latest version of the translation.

![translationdownloader](https://github.com/user-attachments/assets/11e7eeae-2501-492e-9fed-3b90199e9efc)

**Comment by steffenrapp** [comment]
Great that you reopened this feature request. I think this makes life a lot easier! 👍🏼
Still, I'd vote for including all of the translations by default because I don't really see a benefit in this approach and I would never maintain my own translations - I'd rather contribute to improve them. But it's your decision and I'm thankful that you picked it up again to improve quality of life. 😃

**Comment by kgraefe** [comment]
> It will always download the latest version of the translation.

Will this be a manual process or does it update automatically?

**Comment by hargata** [comment]
> > It will always download the latest version of the translation.
> 
> Will this be a manual process or does it update automatically?

Manual, no way to track when a translation is updated.

**Comment by hargata** [comment]
> Great that you reopened this feature request. I think this makes life a lot easier! 👍🏼 Still, I'd vote for including all of the translations by default because I don't really see a benefit in this approach over the other one and I would never maintain my own translations - I'd rather contribute to improve them. But it's your decision and I'm thankful that you picked it up again to improve quality of life. 😃

Well, hence why it's a bit of a compromise, but I have made some additional changes and that should cut down a lot more steps in the process. Just added a "Download All Translations" button so you no longer have to search through the list of available translations.

![image](https://github.com/user-attachments/assets/bb2babe6-4b07-442f-ab4e-8ff4b3212a2f)

Basically, in the next release, All you have to do is click the "Download All Translations" button and it will download the latest copy of every translation available. Basically just two steps and that's it. 

Not as automated as bundling the translations into the release itself, but honestly I don't have the time and effort to coordinate translators for a translation phase so this will have to do.

**Comment by kgraefe** [comment]
thank you :-)

**Comment by hargata** [comment]
The translation downloader feature is released.
