### ISSUE TITLE
Vehicles without license plate and OCR of invoices 

### ISSUE THREAD

**Issue by dnlcappy** [hargata/lubelog#65]
Just wondering if there's a possibility to add a vehicle without licence plate being required. 
For project cars etc that id like to keep track of. 

Also wondering if OCR could be added. 
Upload pdf or image of invoice and have it automatically add expense

Thanks

**Comment by hargata** [comment]
You can just put a placeholder text in the license plate field until you get it registered.
There's nothing preventing you from entering "1" for all of the license plates.
OCR will not be implemented because there aren't any good free/open-source libraries with permissive licensing that I can use. If I were to start using commercial libraries I will have to start charging for this app.

**Comment by hargata** [comment]
@Greal-dev go promote your AI slopware somewhere else, your project has nothing to do with LubeLogger, your comment has been deleted and your user profile has been reported for spam.
