### ISSUE TITLE
[Feature Request] Additional Report Customization

### ISSUE THREAD

**Issue by rtrickett337** [hargata/lubelog#702]
It would be great if the vehicle maintenance reports could be customized further. My suggestions are:

1. The ability to replace the LubeLogger logo in the top left with custom logo. Instead have in the footer ‘Created with LubeLogger’ with the logo and url as one suggestion to still give credit.

2. Be able to change the title of the report. For example, I use an instance of LubeLogger dedicated just to my boat and all of its systems. Would be great to have the report say ‘Vessel Maintenance Report.’

3. Show custom fields on reports

Thanks again for making such a great piece of software!

**Comment by hargata** [comment]
Next Release, 

- custom logos will now show up in the report, a footer is added to provide credit to LubeLogger.

- You will now be able to select which columns(including extra fields) to display in the report

![vehiclereportenhancement](https://github.com/user-attachments/assets/1be0070a-c1e4-4999-b4df-09b4b8f117be)

The custom title thing won't be pursued unfortunately, but you can edit the translation to change "Vehicle Maintenance Report" to "Vessel Maintenance Report" if needed before you export the report so that it shows up correctly.

![image](https://github.com/user-attachments/assets/c6bfefb5-49a7-469a-94b7-4cfb466fd07e)

![image](https://github.com/user-attachments/assets/65ecdb0a-6afc-4cac-a95e-dc7a166a8b04)

**Comment by rtrickett337** [comment]
Thank you so much for quickly adding this! Looking forward to the next release :)

I was able to use the translation tool to customize this perfectly for maintaining my boat so thanks for pointing that out! Definitely agree no need to pursue the custom title filed as the translation takes care of that.

Thanks again!

**Comment by hargata** [comment]
Released
