### ISSUE TITLE
LPG

### ISSUE THREAD

**Issue by ilsaul** [hargata/lubelog#705]
Hi,
My car is use Green Fuel (Gasoline) and GPL (Gas).
Start with gasoline and when the engine is warm use LPG.

I don't see LPG in the list and I don't understand if the system can handle two tanks

Can you help me?

**Comment by hargata** [comment]
This is probably not going to be supported since the app wouldn't know when your vehicle switch between fuel types.

**Comment by Pazdikan** [comment]
@ilsaul this is partially possible with tags as said in this comment [issue #34](https://github.com/hargata/lubelog/issues/34#issuecomment-1924970081)

Although I see this as a work-around rather than a feature. My friend's 1.6L 4 cyl turbo car is using 7-10L/100km of LPG, and <1L/100km of gasoline. You can drive 2000 kilometers before refueling gasoline.

Sadly I only understand basics of C#, and I really don't wanna be *that* guy, but it should be fairly easy to code, just make it so that you can enter multiple fuels for one vehicle, and adjust the UI part to allow adding a record of LPG OR gasoline, and filtering by fuel just like you can filter by tags.

**Comment by hargata** [comment]
@Pazdikan the tricky part isn't the input, but the calculation. Most LPG vehicles don't run on LPG exclusively and require gasoline to start/warm up to operating temperature which then automatically switches over to LPG. Example: you start the trip at 1000km on your odometer and both LPG and Gas tanks are full, you refill at 1500km, you used 1L of Gas and 30L of LPG. 

It's very difficult for the app to tell how much distance is covered by Gasoline while the car is warming up and how much is covered by LPG. There are too many factors at play that can affect that, e.g.: some people will let the car sit and idle until it's warm and some will drive around slowly while it warms up.

We(the maintainers) don't own a LPG car nor have we ever driven one, but if we were to own one, we would treat the LPG as the primary fuel source and assume that the entire trip is made with LPG with gasoline covering 0 distance. What we would do, is create two [extra fields](https://docs.lubelogger.com/Advanced/Additional%20Fields) for the Fuel Record Gasoline Consumption and Gasoline Cost, so that we can keep track of how much gasoline is used between fill ups and how much it costs, but these fields won't affect the Fuel Economy calculation.
