### ISSUE TITLE
[Feature Request] Import of aCar *.abp files

### ISSUE THREAD

**Issue by truncsphere** [hargata/lubelog#715]
Would love to see a full import for current aCar file format without having to hack up the CSV export. 
This will allow more users fed up with aCar's current poor upgrade choices to move to another platform.

**Comment by hargata** [comment]
Send me a sample file and I'll see what I can do.

**Comment by hargata** [comment]
After further consideration, I think it's best that we leave this to a community-supported feature instead of building it directly into LubeLogger. We don't use aCar and have zero intentions of utilizing aCar in order to figure out how their data structures work.

**Comment by Steltek** [comment]
For anyone who stumbles upon this and wants to tackle it: The abp files that aCar exports are just ZIP files. They contain several XML files within (and a separate text file with some metadata on aCar itself):
```
event-subtypes.xml
fuel-types.xml
metadata.inf
preferences.xml
sync-metadata.xml
trip-types.xml
vehicles.xml
```

The most interesting file is probably vehicles.xml which contains all the events related to the vehicles, including the fuel records.

**Comment by hargata** [comment]
@Steltek thanks for chiming in, I would also advise anyone willing to tackle this to also consider that the `*.abp` format is potentially proprietary. aCar isn't open-source and doesn't expose an API that can be used to access its data. 

LubeLogger supports CSV imports from multiple services because CSV is an open format, but the moment we tread into proprietary formats is when the legality gets a little fuzzy.

**Comment by truncsphere** [comment]
What I found is I can go to each individual vehicle and then browse records and export to CSV. 
Afterwards I have to edit the CSV to match what Lubelogger will import (just fuel and then just service records)

**Comment by disconn3ct** [comment]
> legality gets a little fuzzy.

Can you please elaborate on that? What country has made reading a file illegal? And does this mean the project will not accept any contributions to read external formats?

**Comment by hargata** [comment]
@disconn3ct obligatory I'm not a lawyer, so our research into this is very limited, but there are precedents of file formats having  restrictive licensing terms such as [DOC](https://en.wikipedia.org/wiki/Doc_(computing)#Specification) and [GIF](https://en.wikipedia.org/wiki/GIF#Unisys_and_LZW_patent_enforcement)

Is it legal to reverse engineer the ABP file format? Probably, after all it only consists of XML files in a zip archive as another comment pointed out. Are we going to chance that and find out in court? Definitely not. The legality is fuzzy at best because we don't know what restrictions Fuelly(which owns aCar) places on the file format and they didn't explicitly state that it's an open format.

Also, Fuelly is backed by [multiple LLCs](https://www.fuelly.com/forums/f41/did-the-owner-of-the-app-21951.html#:~:text=What%20is%20the%20future%20for,Thanks.&text=The%20owner%20of%20this%20company,and%20%22Economy%203%20Investments%22.) and we're not, and since we're all based in the states where everyone can sue even if they don't win, we have zero intention of becoming a defendant since that stuff takes tremendous time and money, something we don't have.

> does this mean the project will not accept any contributions to read external formats?

Correct, legality aside, the whole point of us building this project was so that we don't have to rely on the proprietary, closed-source, cloud-based apps that exists in the market. If someone submits a PR which adds functionality to read ABP files or any other file format from those existing apps and we accept it, we are basically accepting the responsibility to support the reading of that file format down the road including edge cases and any future changes to the format.

We already get a lot of grief from users who can't even be bothered to change the CSV headers so that it can be exported into the app. We're not going to try to support a whole file format that can be subjected to changes at any time. On the bright side, the app has an API which will allow you to import data from external sources so realistically speaking, anyone with a bit of time and scripting skills can write a data importer.

**Comment by disconn3ct** [comment]
> obligatory I'm not a lawyer, so our research

Those pages don't say what you claim they do. Lets look at the DOC page: wikipedia heavily references LibreOffice/OpenOffice. It even mentions the fact that Sun/OO reverse engineered the format, and they link to the [resulting doc](http://sc.openoffice.org/compdocfileformat.pdf) (pdf) What Wikipedia does not mention is any resulting lawsuit, because there was not one. It is expressly legal, even in Utah, to "clean-room" reverse engineer file formats (output files are 'artifacts' fyi.) If you want to reference Wikipedia for legal advice, you should start with [this section](https://en.wikipedia.org/wiki/Reverse_engineering#United_States).

You are coming across as someone posturing a legal justification for their feelings. If you don't want external contributions, or external formats, or whatever, just say so. Don't be whatever that mess was.

> We already get a lot of grief from users

Thanks for the big heads up. I hadn't initially realized this was that sort of project. I'll see myself out. BTW don't forget to turn on stalebot.

**Comment by hargata** [comment]
@disconn3ct bye felicia.
