### ISSUE TITLE
[Feature Request] Total Cost of Ownership (Buy Price included) 

### ISSUE THREAD

**Issue by HxNetwork** [hargata/lubelog#750]
Hey,

It would be very nice to have an overview of the TCO with the buy price included.

Maybe also a calculation for monthly costs since purchase (optional until sell date with the sell price). This would be very helpful for comparing the costs of buying and maintaining a car vs. leasing or a "car subscription."

Thanks for the great work so far!

**Comment by hargata** [comment]
This feature already exists(somewhat) in the form of depreciation per day when purchase price/date and a sold price(scrap value) is provided in the vehicle details. Sold Date is entirely optional for this to work.

https://docs.lubelogger.com/Vehicles/Vehicle%20Management#purchase-and-sold-information

This figure is calculated and displayed separately from the maintenance costs of the vehicle, this decision was made **intentionally** so that the maintenance cost figure is not skewed by the purchase cost of the vehicle, nor will it be affected by selling the vehicle.

They are both displayed in the Vehicle Maintenance Report so that the user have the option of tallying up the total cost of ownership if they want to, it's the same line of reasoning for separating the fuel expenses out from the other costs:

![](https://docs.lubelogger.com/Vehicles/Vehicle%20Management/a/image-1726782180243.png)
